name: jose
description: Javascript Object Signing and Encryption (JOSE) library supporting JWE, JWS, JWK and JWT
version: 0.1.3
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/jose

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crypto_keys: ^0.1.2
  meta: ^1.1.6
  typed_data: ^1.0.0
  x509: ^0.1.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0

